
import webbrowser, json, requests
"""Interface with the Cat API"""
class CatAPI:
    global API_KEY
    # this is the api key that on gets from signing up on thecatapi.com, you must register to get it
    API_KEY = "live_pGPtu252IVJfrslX8KvUkqhFOmid15pf8qL7r2PqXiPlnEwYzg7JWGC2MZdwTW4u"

def get_img():
    url = "https://api.thecatapi.com/v1/images/search?api_key=" + API_KEY

    # download the file found on the web that is generated by the api call
    myfile = requests.get(url)
    file = open('cat_data.json', 'wb')
    file.write(myfile.content)    
    file.close()
    
    # open the json file and the make it into a dictionary
    file = open ('cat_data.json', "r")
    # https://www.geeksforgeeks.org/read-json-file-using-python/
    data = json.loads(file.read())  
    file.close()

    cat_url = data[0].get("url")

    # open the url found in the json file and put it in a message
    webbrowser.open(cat_url)
    message = "Image transfer success! Open your browser or click the link here: " + cat_url
    return message




    
